### ISSUE TITLE
Freezing Emulator, Missing TextAssets and Missing Texture(s)

### ISSUE THREAD

**Issue by ghost** [fasteddo/mcs#2]
Sadly, there isn't much information given on this project, such as where to put the roms in the Unity project (and in the build). I got this to run and compile fine with no errors, and the cursor, mouse and buttons all work, but when you click on an emulator button like "Available" or "ENTER" then the emulator freezes (along with the emulator cursor. The Unity project and debug window are still running fine, but the emulator window is frozen (showing the game list).

Steps to reproduce:
-Run MCS
-Start Emulator
-Choose any game and press "Enter". Also, the emulator freezes if you click on (or hit Enter on) any of the emulator catagories on the left, like "Available" or "Working". It also freezes if you click on "Configure Options" or the other buttons. The "Exit" button works properly though.
![p2](https://user-images.githubusercontent.com/30076916/111557278-bcdbd380-8762-11eb-9153-43a0362ac476.png)

I am aware that the missing TextAssets might be the cause of the problem, and the TextAssets are likely the rom files, but I am still not sure why I can't access the configuration so far, or see what roms are "Available" without the emulator crashing.
![p3](https://user-images.githubusercontent.com/30076916/111557225-a766a980-8762-11eb-9011-b3bb5ee8fa35.png)

Also, there seems to be a missing texture, there is a pink screen showing before the emulator is started.
![p1](https://user-images.githubusercontent.com/30076916/111557244-af264e00-8762-11eb-826d-983d201a9118.png)

More information on the project would be nice, there is no real "ReadMe" file either, but I will continue to try to piece it back together.

**Comment by fasteddo** [comment]
Hello,
Apologies for such a late reply.  I was never notified that new issues were created.
There have been a few updates since this was posted.  Could you please try again and let me know if you have more success?
Also, the mcsForm project is kept more up-to-date than the Unity project.  So, if you run into specific Unity issues, try the mcsForm and see if it happens there as well.
Also, understand this is just a hobby project.  Happy to have to help!
Thank you!

**Comment by ghost** [comment]
I do have some technical experience, but the best I could get it to work was running the games but almost every button on the emulator freezes the emulator but **not** the Unity project which stays running fine. -I will try the mcsForm projects for any updates though and see if it works.
